title: Billy Wu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I work for the University of Auckland in the field of public health. My areas of expertise include data management, big data manipulation, analytics interface development, and machine learning for classification.
  <br><br>
  
theme: jekyll-theme-minimal
